### ISSUE TITLE
modify the READme section

### ISSUE THREAD

**Issue by Adyasha8105** [smaranjitghose/profile_chrome_extension#5]
Here, I want to modify the readme section as it contains too many images.

**Comment by smaranjitghose** [comment]
Can you please elaborate more?
Well, the text and gifs need to be aligned as well

**Comment by Adyasha8105** [comment]
> Can you please elaborate more?
> Well, the text and gifs need to be aligned as well

Yes sir and it contains too much of GIFs

**Comment by smaranjitghose** [comment]
> > Can you please elaborate more?
> > Well, the text and gifs need to be aligned as well
> 
> Yes sir and it contains too much of GIFs

Actually, I am planning to use the markdown file to make a blog, hence to make it interactive i would suggest having the gifs for now
